### PR TITLE
Add support for tracking user timings

### PR DESCRIPTION
**Pull request by tjokimie**
Add support for tracking user timings.

* [Universal Analytics user timings](https://developers.google.com/analytics/devguides/collection/analyticsjs/user-timings)
* [Classic Analytics user timings](https://developers.google.com/analytics/devguides/collection/gajs/gaTrackingTiming)

### CODE REVIEW

**Comment by mgonto** [comment]
Thanks for the PR!

Looks awesome :).

Merging!

**Comment by tjokimie** [comment]
Thanks! :) Any chance of getting a new release for this?

**Comment by mgonto** [comment]
Yep, I'll do it tomorrow :).

**Comment by tjokimie** [comment]
Superb! :+1:

**Comment by mattrw89** [comment]
I'm excited about this being released! Thanks for writing it @tjokimie and releasing it @mgonto!

**Comment by mgonto** [comment]
Sorry for the delay, I went on vacations and just came back.

Bumped as 0.4.0 :). And adding History from now on.

Cheers!

**Pull request merged**
